import Head from "next/head";
import type { InferGetStaticPropsType } from "next";
import { getAllProducts } from "@framework/product";
import { getConfig } from "@framework/api/config";
import { Layout } from "@components/common";
import { ProductCard } from "@components/product";
import { Grid } from "@components/ui";
import { Hero } from "@components/ui/Hero/Hero";
import Marquee from "@components/ui/Marquee/Marquee";

export async function getStaticProps() {
  const config = getConfig();

  const products = await getAllProducts(config);
  return {
    props: {
      products,
    },
    revalidate: 4 * 60 * 60,
  };
}

export default function Home({
  products,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div className="mx-44">
          <Grid>
            {products.slice(0, 3).map((product) => (
              <ProductCard key={product.id} product={product} />
            ))}
          </Grid>
        </div>
        <div className="hidden">
          <Hero headline="This is Hero section" description="Live Laugh Code" />
        </div>
        <div className="hidden">
          <Marquee>
            {products.slice(0, 3).map((product) => (
              <ProductCard key={product.id} variant="slim" product={product} />
            ))}
          </Marquee>
        </div>
        <div className="hidden">
          <Grid layout="B">
            {products.slice(0, 3).map((product) => (
              <ProductCard key={product.id} product={product} />
            ))}
          </Grid>
        </div>
        <Marquee variant="secondary">
          {products.slice(0, 3).map((product) => (
            <ProductCard key={product.id} variant="slim" product={product} />
          ))}
        </Marquee>
      </>
    </div>
  );
}

Home.Layout = Layout;
