import Head from "next/head";
import type { InferGetStaticPropsType } from "next";
import getAlLProducts from "../framework/shopify/product/get-all-products";
// import getAlLProducts from "@framework/product/get-all-products";
import { getConfig } from "@framework/api/config";
import { Layout } from "@components/common";

export async function getStaticProps() {
  const config = getConfig();

  const products = await getAlLProducts(config);
  return {
    props: {
      products,
    },
    revalidate: 4 * 60 * 60,
  };
}

export default function Home({
  products,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{JSON.stringify(products)}</h1>
    </div>
  );
}

Home.Layout = Layout;
